[profile.default]
solc_version = '0.8.24'
evm_version = 'cancun'
optimizer = true
optimizer-runs = 200
src = 'contracts'
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "closedzeppelin-contracts/=contracts/"
]